### ISSUE TITLE
Downloaded and unpacked into Chrome

### ISSUE THREAD

**Issue by samirrah** [SolaceMotion/Symbolab-Pro#2]
Not sure if I'm using this incorrectly, or that the extension is patched. I have the program showing up in my list of Chrome extensions, however, I am not able to view steps on Symbolab.

**Comment by SolaceMotion** [comment]
Hi, sorry for my late response. You might be right about it having been patched. This is not a repository I actively maintain so the chance is definitely there. Knowing this I may archive the repo.
